# code: language=ansible
---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    ## テストの前処理
    - name: Gather user facts
      ansible.builtin.getent:
        database: passwd
    - name: Set assert variables
      ansible.builtin.set_fact:
        registered_users: "{{ ansible_facts.getent_passwd }}"
